version: '2.28' # Adjust if needed based on your docker-compose version

services:
  vpet_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=vpetadmin
      - POSTGRES_PASSWORD=vpetpassword
      - POSTGRES_DB=vpetdatabase
    volumes:
      - vpetvolume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  vpetvolume:
